import { sortNumber, sortText, sortDateFromString } from '@/components/beatmap/table/function/BeatmapsTableSortFunctions';

enum BeatmapsTableHeadersTemplate {
  Text = 'Text',
  Cover = 'Cover',
  Difficulties = 'Difficulties',
  StrToDate = 'StrToDate',
  TextTooltip = 'TextTooltip',
  BeatmapName = 'BeatmapName',
  Rating = 'Rating',
}

export interface BeatmapsTableHeader {
  value: string,
  text: string,
  template: BeatmapsTableHeadersTemplate,
  align?: 'start' | 'center' | 'end',
  width?: number,
  sortable?: boolean,
  filterable?: boolean,
  sort?: (a: any, b: any) => number,
  filter?: (value: any, search: string, item: any) => boolean,
  templateItemAccess?: string,
}

export const headers = [
  {
    value: 'cover',
    text: 'Cover',
    template: BeatmapsTableHeadersTemplate.Cover,
    align: 'left',
    sortable: false,
    width: 48,
  },
  {
    value: 'name',
    text: 'Song name',
    template: BeatmapsTableHeadersTemplate.BeatmapName,
    align: 'left',
    sortable: true,
    sort: sortText,
  },
  {
    value: 'artist',
    text: 'Artist',
    template: BeatmapsTableHeadersTemplate.TextTooltip,
    templateItemAccess: 'metadata.songAuthorName',
    align: 'left',
    sortable: true,
    sort: sortText,
  },
  {
    value: 'mapper',
    text: 'Mapper',
    template: BeatmapsTableHeadersTemplate.TextTooltip,
    templateItemAccess: 'metadata.levelAuthorName',
    align: 'left',
    sortable: true,
    sort: sortText,
  },
  {
    value: 'difficulties',
    text: 'Difficulties',
    template: BeatmapsTableHeadersTemplate.Difficulties,
    templateItemAccess: 'metadata.difficulties',
    align: 'left',
    sortable: false,
  },
  {
    value: 'dl',
    text: 'Downloads',
    template: BeatmapsTableHeadersTemplate.Text,
    templateItemAccess: 'stats.downloads',
    align: 'center',
    sortable: true,
    sort: sortNumber,
  },
  {
    value: 'plays',
    text: 'Plays',
    template: BeatmapsTableHeadersTemplate.Text,
    templateItemAccess: 'stats.plays',
    align: 'center',
    sortable: true,
    sort: sortNumber,
  },
  {
    value: 'upvotes',
    text: 'Up votes',
    template: BeatmapsTableHeadersTemplate.Text,
    templateItemAccess: 'stats.upVotes',
    align: 'center',
    sortable: true,
    sort: sortNumber,
  },
  {
    value: 'downvotes',
    text: 'Down votes',
    template: BeatmapsTableHeadersTemplate.Text,
    templateItemAccess: 'stats.downVotes',
    align: 'center',
    sortable: true,
    sort: sortNumber,
  },
  {
    value: 'rating',
    text: 'Rating',
    template: BeatmapsTableHeadersTemplate.Rating,
    templateItemAccess: 'stats.rating',
    align: 'center',
    sortable: true,
    sort: sortNumber,
  },
  {
    value: 'uploaded',
    text: 'Uploaded',
    template: BeatmapsTableHeadersTemplate.StrToDate,
    templateItemAccess: 'uploaded',
    align: 'center',
    sortable: true,
    sort: sortDateFromString,
  },
  {
    value: 'key',
    text: 'Key',
    template: BeatmapsTableHeadersTemplate.Text,
    templateItemAccess: 'key',
    align: 'center',
    sortable: false,
    sort: sortNumber,
  },
  {
    value: 'hash',
    text: 'Hash',
    template: BeatmapsTableHeadersTemplate.Text,
    templateItemAccess: 'hash',
    align: 'center',
    sortable: false,
    sort: sortNumber,
  },
] as BeatmapsTableHeader[];
